name: Categorizar datos

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn openpyxl matplotlib

      - name: Run categorization script
        run: python categorizar.py

      - name: Upload categorized data
        uses: actions/upload-artifact@v2
        with:
          name: INSUMOS 2023_MAY 2024 (version 1)
          path: INSUMOS 2023_MAY 2024 (version 1).xLsx

      - name: Upload elbow method plot
        uses: actions/upload-artifact@v2
        with:
          name: elbow-method
          path: elbow_method.png
